name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project dependencies

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel  # Build the source and wheel package

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__  # Username for PyPI token-based authentication
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # Reference to your secret
        run: twine upload dist/*
